version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - my-net

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "android:1:1,acceleration:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - my-net
    depends_on: 
      - zookeeper

  zeppelin:
    ports:
      - 8080:8080
      - 4040:4040
    volumes:
      - /Users/sowjanyabojja/Downloads/Sowji/FraudAnalysis/spark248:/opt/spark
    environment:
      - SPARK_HOME=/opt/spark
    image: apache/zeppelin:0.10.0
    networks:
      - my-net

  mysql:
    container_name: mysql
    privileged: true
    environment:
      - GRANT_SUDO=yes
      - MYSQL_USER=jack
      - MYSQL_PASSWORD=abc
      - MYSQL_ROOT_PASSWORD=abc
      - MYSQL_DB= FRAUDSDB
    user: root
    volumes:
      - "./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    ports:
      - 3306:3306
    restart: always
    image: mysql:5.7
    networks:
      - my-net

  consumer:
    build: consumer/.
    volumes:
      - /Users/sowjanyabojja/Downloads/Sowji/FraudAnalysis/spark248:/opt/spark
    environment:
      - SPARK_HOME=/opt/spark
    networks:
      - my-net
    depends_on: 
      - kafka

  web:
    build: askme/.
    ports:
      - 8000:8080
    networks:
      - my-net

  producer:
    build: producer/.
    ports:
      - 5000:5000
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
